export const newsFeedMessages = [
    "🚨 Breaking news! A turbo-powered signing just dropped.",
    "🏎️ New racer in the garage — speed guaranteed.",
    "💥 Massive move in the market. Nobody saw this coming!",
    "⚙️ Team upgrades complete. Let’s hit the track.",
    "⚡ This racer brings pure chaos and drift energy.",
    "🍌 Careful — this signing comes with banana-level danger.",
    "🎯 Precision pick. Straight to the podium.",
    "🔥 The new recruit is here to melt the track.",
    "🏆 With this move, the team aims for glory.",
    "🛞 New driver, same hunger for first place.",
    "🚦 Lights out and away we go — new transfer confirmed!",
    "🎮 “Ready, set… recruit!”",
    "🧠 Genius move or total madness? We’ll find out soon.",
    "💣 Blue shell transfer — direct hit on the rivals.",
    "🍄 Power-up unlocked: new racer activated.",
    "🌈 Rainbow Road energy — unpredictable and brilliant.",
    "⛽ Full tank, full hype.",
    "🧩 The missing piece just joined the puzzle.",
    "🪄 From rumor to reality: magical signing confirmed.",
    "🧤 They’ve been watching this one for weeks.",
    "🚀 Podium, brace yourself. This one’s flying.",
    "🪙 Expensive, but absolutely worth it.",
    "💬 “Was it luck or strategy? Doesn’t matter, it worked.”",
    "🕹️ Full control: team boosted.",
    "👀 Everyone wanted them, but only one got them.",
    "🏎️ A transfer that leaves tire marks everywhere.",
    "⚙️ Building the dream kart, one racer at a time.",
    "💫 This new face brings pure starlight energy.",
    "🧨 Explosive transfer — no one saw it coming!",
    "🪶 Light, fast, and deadly. Perfect combo.",
    "🧃 Fresh move, hot potential.",
    "🏁 “Toad said it best: this team’s going places!”",
    "🧊 Cold move, hot result.",
    "🪩 Glamour meets gasoline.",
    "🧩 “Now it all makes sense.”",
    "💪 New racer, new dreams.",
    "🍄 Time for a comeback! Turbo mode ON.",
    "🧭 Steering straight for victory.",
    "💥 The market’s on fire and this signing is the reason.",
    "🎢 A wild ride ahead for this new team.",
    "🧤 From the bench to the main track.",
    "🪙 A golden deal — literally.",
    "🧠 200 IQ move: absolute brilliance.",
    "🧨 “Boom! Transfer unlocked.”",
    "🏆 The championship race just got interesting.",
    "🧊 Ice cold signing.",
    "🚀 Straight to the top three.",
    "🧩 A surprise pick that shakes the rankings.",
    "🍌 Someone just dropped a banana in the transfer market.",
    "🌪️ This racer’s about to blow everyone away.",
    "🏁 Game changer alert!",
    "🧃 Mid-season refresh: new driver incoming.",
    "🔥 “While you were sleeping, I was signing legends.”",
    "🏎️ That name alone causes fear.",
    "💨 They signed them before the finish line.",
    "🧤 The pit crew just got serious.",
    "🪄 Magic move, flawless execution.",
    "🍄 Speed + strategy = perfect pick.",
    "🏆 “This will be my year.” — everyone after signing them.",
    "💣 The market explodes with this deal.",
    "🧊 Cool driver, hot results.",
    "🚀 Nobody expected it, but everyone’s jealous.",
    "🧩 One piece that changes everything.",
    "🎮 Level up achieved — new racer joined.",
    "🧃 “I just trust my luck.”",
    "🏎️ Rumor confirmed. Let the chaos begin.",
    "⚡ Lightning-fast move.",
    "🏁 Another one joins the winner’s club.",
    "🪙 Premium signing, maximum hype.",
    "🧠 Big brain plays only.",
    "🍌 Not sure if genius or disaster.",
    "🏎️ The race just changed course.",
    "🔥 “If I lose, I’ll lose in style.”",
    "🎯 Risky pick, high reward.",
    "🧃 Fresh fuel, fresh energy.",
    "🪩 Rainbow Road vibes only.",
    "🧤 Pedal to the metal — the market is wild.",
    "🧊 Cold hands, hot wheels.",
    "🪙 Worth every coin.",
    "🏁 When the market becomes a racetrack.",
    "⚡ Signed at the speed of lightning!",
    "🎮 “Press A to confirm transfer.”",
    "🏎️ The season just got serious.",
    "🧩 Building the dream one drift at a time.",
    "🍄 More mushrooms, fewer mistakes.",
    "🧤 Tactical move with max grip.",
    "💥 Another player bets it all.",
    "🏁 The market never sleeps.",
    "🧃 “Either my best move… or my most expensive mistake.”",
    "🧠 Strategy > luck (hopefully).",
    "🏎️ The engine roars — new signing confirmed.",
    "⚙️ Reinventing the lineup, one lap at a time.",
    "🧩 Surprise pick that shakes the standings.",
    "🪙 Broke, but happy.",
    "🏁 Last second transfer. Pure adrenaline.",
    "💣 “I did it for the drama.”",
    "🚦 The grid shakes after this signing.",
    "🌈 Legendary move — history made.",
    "🎮 “Insert coin to upgrade your team.”",
    "🏆 One word: domination."
];
